### ISSUE TITLE
US 4: Add new Book Part 1( Searchbar)

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-fullstack-readspark#11]
# Value proposition
As a user,
I want to search after a book and add it to my existing books,
so I have it in my list and could add it to my favorites later.

# Description
There will be a search bar component. As soon as I write a book name, the search bar expands to a drop-down menu, like an autocomplete component.
The desired book can then be selected there. 
With an add button, the book is then added to the book collection and the db.

# Acceptance criteria
- [ ] the searchbar is working
- [ ] as soon as there is a book name, the searchbar expands
- [ ] the cover and title are visible
- [ ] every book is choosable
- [ ] when the book is clicked, the book details are visible
- [ ] the add button is working and add the book to the book collection in the frontend and backend

# Tasks
- [ ] create a new branch named "feat/add-book-searchbar"
- [ ] create BookDto
- [ ] create the AddNewBook component
- [ ] create the search component
- [ ] add the needed functions (SearchResult, handleAddBook)
- [ ] add the POST-Mapping for the backend

# Size
L
