### ISSUE TITLE
US 1: Database

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-fullstack-readspark#5]
# Value proposition
As a developer
I want to create a database with the needed collections and values,
so I can work with the saved data in my back- and frontend

# Description
Not needed

# Acceptance criteria
- [ ] Every needed collection is visible
- [ ] Every collection has some value in it

# Tasks
- [ ] create the needed data for the books collection 
- [ ] create a new collection named "lists"
- [ ] fill the lists- collection with the needed data

# Size
S
