### ISSUE TITLE
US 2: Get all books

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-fullstack-readspark#6]
# Value proposition
As a user,
I want to see all of my added books at the start/ overview page,
so I can scroll through my books and select one.

# Description
will be updated

# Acceptance criteria
- [x] At the starting- / Overview page, every book is listed and clearly readable

# Tasks
- [x] create a new branch named "feat/get-all-books"
- [x] create every model, service, controller etc.  needed
- [x] implement the GET Method for the backend
- [x] create the first frontend component "book card"
- [x] create the "allBooks" component
- [x] import axios for the frontend to connect with the backend
- [x] add Tests

# Size
M
