### ISSUE TITLE
US 3: BookDetailPage

### ISSUE THREAD

**Issue by JanaS87** [JanaS87/capstone-fullstack-readspark#9]
# Value proposition
As a user,
I want to see all necessary informations about a book at a glance,
so I know from which author, for example, it is.

# Description
![IMG_0014](https://github.com/JanaS87/capstone-fullstack-readspark/assets/136725332/d9272783-c5ce-4c80-8c6f-779915fbca96)

# Acceptance criteria
- [ ] every book is clickable and leads to its detail page
- [ ] the detail-page shows the cover, title, author etc.
- [ ] everything is clearly visible and readable
- [ ] the "back" button leads back to the overview- page

# Tasks
- [ ] create new branch named "feat/detail-page"
- [ ] create detail page component
- [ ] implement axios for getBookById
- [ ] implement extern api for book cover
- [ ] create "back"- Link with Routing and CSS

# Size
M
